### ISSUE TITLE
Unhandled: Cannot find module 'q'

### ISSUE THREAD

**Issue by Eckham** [Microsoft/vsts-extension-build-release-tasks#1]
Set workingFolder to default: 
C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.100.1\tasks\PackageVSTSExtension\0.6.1
Unhandled: Cannot find module 'q'

(Using "Hosted Service")

**Comment by bfcamara** [comment]
Hi @Eckham - is this error consistent and happens all the time whenever you queue your build? It seems that some task artifacts were now downloaded to the build agent.

**Comment by Eckham** [comment]
Hi  @bfcamara,

The error happens every build. I attached the logs. I already have a build definition with a custom solution using grunt to deploy the extension. There all works fine. (so I can validate that my extension is working)

[1_Build.txt](https://github.com/Microsoft/vsts-extension-build-release-tasks/files/304728/1_Build.txt)
[5_Package Extension $TfsAxExtensionsDevSDK4NET.TfsExtensions.AXSDK4NET.TfsExtensions.AX.txt](https://github.com/Microsoft/vsts-extension-build-release-tasks/files/304729/5_Package.Extension.TfsAxExtensionsDevSDK4NET.TfsExtensions.AXSDK4NET.TfsExtensions.AX.txt)

**Comment by bfcamara** [comment]
@Eckham - I am not being able to repro the problem. Would you be available for a skype call?

Could you try to create a new empty build definition with just one build step configured to use the "Package Extension" (the task args are irrelevant) and then Queue a build and check if you get the same error?

**Comment by bfcamara** [comment]
I think we found the problem - a VSIX packaging and versioning issue. I've just published a new version 0.7.2. Could you try a new build please?

**Comment by Eckham** [comment]
The complete process is working for my Microsoft Dynamics AX Build Tools now. Build an VSIX with overriding some metadata, Deploy the VSIX to the marketplace and Upload the Artifacts with the output variable. Amazing! Great job, guys!

**Comment by bfcamara** [comment]
Cool. Thanks for reporting the issue.

**Comment by jessehouwing** [comment]
I've been trying to build a local version of the extension, and I'm running into the same issue with the latest package.json.
