### ISSUE TITLE
Support for External TFS service endpoints in install tasks

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/vsts-extension-build-release-tasks#10]
The publish and install tasks only allow for marketplace service endpoints. I would like to see the filter expanded to allow for External TFS service endpoints as well. For that matter, why doesn't it show "Visual Studio Marketplace" endpoints? Only "Marketplace".

**Comment by bfcamara** [comment]
There is some work in progress to make these tasks work with external TFS Onprem endpoints. In fact, the version that is in master now (0.7.4) already supports TFS Onprem, however for some reason it was not published yet to the marketplace (still 0.7.3). 

The install task neesd some tfx-cli changes in order to work with TFS Onprem. There is a PR being reviewed.

https://github.com/Microsoft/tfs-cli/pull/132

**Comment by jdshkolnik** [comment]
Why do they differentiate between "Marketplace" and "Visual Studio Marketplace" endpoints? Is there a difference?

**Comment by bfcamara** [comment]
This VSTS extension defines a new service endpoint type to connect to the Visual Studio Marketplace by using a personal access token, which has its display name as `Marketplace`. Then, these tasks, when asking for the endpoint, they are filtering by this new type. Semantically speaking, Visual Studio Marketplace or Marketplace, in the context of the tasks provided by this extension, they have the same meanning.

**Comment by jessehouwing** [comment]
Also, for the TFS marketplace we need to user to provide the service endpoint location. For VSTS the endpoint location is known and fixed, so we don't provide the user  the option to set it.

**Comment by jdshkolnik** [comment]
We get personal access tokens for onprem with 2017 but the extension assumes VSTS when token-based authentication is selected.

**Comment by jessehouwing** [comment]
@jdshkolnik we'll need to extend the service endpoint definition for the TFS endpoint to also support apitoken.

**Comment by jessehouwing** [comment]
First thing is to get a new version out that has the features that were added in the past months. I'm working directly with the ALM Rangers to setup what's needed to validate this. Afterwards I'll start adding a few of the enhancements.

**Comment by jessehouwing** [comment]
Fixed in: https://github.com/Microsoft/vsts-extension-build-release-tasks/tree/users/jessehouwing/libs-update

**Comment by aumanjoa** [comment]
Hey,

is this change still pending because of the missing implementation of https://github.com/Microsoft/tfs-cli/pull/132? Any timeline for that?

**Comment by jessehouwing** [comment]
Still waiting for that change. The pull request is outdated by now and can no longer be merged.

**Comment by trevorsg** [comment]
Work is completed on the tfx-cli side.

`tfx extension install --service-url http://tfsserver:8080/tfs/DefaultCollection --token <PAT> --vsix myextension.vsix`

**Comment by jessehouwing** [comment]
The tasks just hides the input if I remember correctly. I'll set aside some
time to get them re-enabled.

**Comment by jessehouwing** [comment]
Added to #62. Work in progress,
