### ISSUE TITLE
Support for Build Tasks 

### ISSUE THREAD

**Issue by SebastiaanPolfliet** [Microsoft/vsts-extension-build-release-tasks#101]
It would be nice to have (more or less) the same functionality of publish extensions available for uploading build tasks (see upload https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md). This would simplify uploading a build tasks substantially.

**Comment by jessehouwing** [comment]
The guidance is to package your build tasks in an extension.

**Comment by SebastiaanPolfliet** [comment]
Good point 👍
