### ISSUE TITLE
Visual Studio marketplace publish

### ISSUE THREAD

**Issue by laurentkempe** [Microsoft/vsts-extension-build-release-tasks#103]
When do you plan to have Visual Studio marketplace publish available?

**Comment by jessehouwing** [comment]
Another MVP has volunteered to do that work. At the moment I do not know his exact timelines. If you'd like to contribute, that'd be appreciated.

**Comment by jessehouwing** [comment]
We'd love that! I'll take pull requests on this. The idea is as follows:

 * New Publish Visual Studio Extension task
 * Re-use existing infrastructure, access tokens, service connections etc
 * Make the UI a close as possible to the existing Publish task
 * First version would publish as-is.
 * Clearly mark the task as Preview.
 * Create a Tool Installer task to install the vsix publisher executables and dependencies
 * Set the correct Demands

Language of choice:
 * Typescript



Then later add:
 * Override Publisher
 * Override Extension ID
 * Override Version
 * etc.

**Comment by jessehouwing** [comment]
@onlyutkarsh has previously also shown interest and the current state of the tasks in good enough to accept serious extensions again. That has taken a while :).

**Comment by jessehouwing** [comment]
@onlyutkarsh any update?

**Comment by onlyutkarsh** [comment]
> @onlyutkarsh any update?

I should be able to make a pull request by Sunday. Got it working almost. Sorry for being slow here - totally occupied with work :-(

**Comment by onlyutkarsh** [comment]
@jessehouwing you will pull this into master or someone from MS will have to do?

**Comment by jessehouwing** [comment]
I can do it. Had my laptop implode on me yesterday, recovering.
