### ISSUE TITLE
Error when installing from Marketplace to Azure DevOps Server 2019 RC1

### ISSUE THREAD

**Issue by scrthq** [Microsoft/vsts-extension-build-release-tasks#107]
Error text:

```text
All the task versions belonging to Contribution is-valid-extension-build-task should have the same task id. The tasks at BuildTasks/IsValidExtensionAgent/task.json (version 1.2.8) and BuildTasks/IsValidExtension/task.json (version 1.2.8) do not have the same ids.
```

Screenshot:

![image](https://user-images.githubusercontent.com/12724445/49848392-89978680-fd9a-11e8-8104-e4a3135fb00b.png)

**Comment by pkuma-msft** [comment]
Hi @scrthq , just confirming that you are installing the extension on TFS in connected context as described here? https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=tfs-2018

**Comment by scrthq** [comment]
@pkuma-msft - That is correct! Installing directly from Marketplace in connected context.

**Comment by scrthq** [comment]
@pkuma-msft - Tested from my personal Azure DevOps Services (previously VSTS) account and I am unable to replicate there; it installs fine. Seems to be scoped to our on-prem Azure DevOps Server 2019 RC1 build. All other extensions have installed without issue so far.

**Comment by scrthq** [comment]
@pkuma-msft - Let me know if you'd like me to try downloading and installing it via the disconnected context.

**Comment by pkuma-msft** [comment]
Yes, would be great if you can try downloading and installing. Though I don't expect that to work either, it'll be a data point for the partner team investigating it. Thanks!

**Comment by scrthq** [comment]
Tried downloading and installing manually, but received an error stating that the extension is already installed when I attempted installing. Checking my installed extensions via Manage Extensions shows it there, but it's not available on any of my collections (not even as a disabled extension).

### Not available on any collection extension list:

![image](https://user-images.githubusercontent.com/12724445/50014070-8366fd00-ff88-11e8-9435-4277825b7dd7.png)

***

### Visible when browsing local extensions:

![image](https://user-images.githubusercontent.com/12724445/50014121-a85b7000-ff88-11e8-91a4-4cf5663c5a01.png)

***

### Visible from the Manage Extensions view also:

![image](https://user-images.githubusercontent.com/12724445/50014185-d640b480-ff88-11e8-927a-ce3be6d1700f.png)

**Comment by jessehouwing** [comment]
Fixed in Azure DevOps Server 219 RC2

**Comment by scrthq** [comment]
@jessehouwing thanks, Jesse! Any available ETA on RC2 and/or GA release?

**Comment by scrthq** [comment]
@jessehouwing no worries, I understand! Worth asking just in case. Thanks for the help regardless!

**Comment by jessehouwing** [comment]
https://blogs.msdn.microsoft.com/devops/2019/01/22/azure-devops-server-2019-rc2-now-available/
