### ISSUE TITLE
On-Prem build agent not updating tfx version

### ISSUE THREAD

**Issue by carlowahlstedt** [Microsoft/vsts-extension-build-release-tasks#111]
I was trying to publish a new task to my local org account and got an error back:

`2019-02-11T16:17:37.3840977Z error: Failed Request: Internal Server Error(500) - The stated category 'Build and release' is no longer supported. Refer to the categories listed at https://aka.ms/extensioncategories and republish using one or more amongst them. 0 [ 'error: Failed Request: Internal Server Error(500) - The stated category \'Build and release\' is no longer supported. Refer to the categories listed at https://aka.ms/extensioncategories and republish using one or more amongst them.',`

After updating the category to `Azure Pipelines`, the build failed with:

`2019-02-11T16:20:24.7232096Z error: The following categories are not valid: Azure Pipelines. Valid categories are: Build and release, Collaborate, Code, Test, Plan and track, Insights, Integrate, Developer samples.`

I checked the `tfx` version being used and it was `0.5.10`. I removed tfx from the local tools folder and ran the build again. This time it installed v `0.6.4` of tfx. It seems the task is not properly updating to the latest version, if a previous version exists.

**Comment by jessehouwing** [comment]
That's correct it tries to detect a locally installed version and uses that.

You can use `npm update tfx@^0.6` in a prior task to force it to stay updated.

I've considered updating automatically, but that would be a breaking change to the way the tasks currently works.

I've wanted to create a tool installer instead where you can specify which version strand to use.

**Comment by carlowahlstedt** [comment]
Have you considered adding an optional setting to keep the tool up to date?

**Comment by jessehouwing** [comment]
I did. I prefer the tool installer, as people tend to use more than one task from this suite in their pipeline and that way this can all be handled in one go. Simply using the npm task to install the tool somewhere and then configuring the toolpath also works.
