### ISSUE TITLE
Package extension manifest-globs errors

### ISSUE THREAD

**Issue by BiribiriJaNai** [Microsoft/vsts-extension-build-release-tasks#115]
Hi,
I am working on an extension structured like this (details omitted):
```
.
|-- endpoints-extension-dev.json
|-- endpoints-extension.json
|-- package.json
|-- src
|   |-- contrib1.json
|   |-- contrib2.json
|   `-- contrib3.json
`-- static

```
All contributions are place in the `src` folder, and I have two main manifest files, one for development, one for production. The only difference between them is the extension id and its display Name.

I can create both extensions (dev and prod) using scripts defined in the `package.json` file:
```
  "scripts": {
    "clean": "rimraf ./dist/* *.vsix",
    "package:dev": "tfx extension create --manifest-globs endpoints-extension-dev.json ./src/*.json --output-path ./dist/dev",
    "package:prod": "tfx extension create --manifest-globs endpoints-extension.json ./src/*.json --output-path ./dist/prod",
    "package": "npm run clean && npm run package:dev && npm run package:prod"
  },

```

I tried to use the 'Package Extension' task using the same parameters, but I always get the same error message, 'No manifests found from the following glob patterns':

```
##[debug]outputVariable=Extension.OutputPath
##[debug]rootFolder=/home/adminuser/agent03/_work/17/s
##[debug]patternManifest=endpoints-extension-dev.json src/*.json
##[debug]publisherId=null
##[debug]localizationRoot=/home/adminuser/agent03/_work/17/s
##[debug]extensionId=null
##[debug]extensionTag=null
##[debug]method=null
##[debug]fileType=null
##[debug]extensionName=null
##[debug]extensionVisibility=default
##[debug]extensionPricing=default
##[debug]extensionVersion=0.1.0
##[debug]Overriding extension version to: 0.1.0
##[debug]noWaitValidation=null
##[debug]bypassLocalValidation=false
##[debug]Generating Build temp file: /tmp/PackageTask-0.631205.tmp
##[debug]Generated a JSON temp file to override manifest values Path: /tmp/PackageTask-0.631205.tmp
##[debug]arguments=null
##[debug]outputPath=/home/adminuser/agent03/_work/17/a/dist/dev/mypublisher.endpoints-dev.vsix
##[debug]updateTasksVersion=false
##[debug]updateTasksId=false
[command]/home/adminuser/agent03/_work/_tools/node_modules/.bin/tfx extension create --json --no-color --root /home/adminuser/agent03/_work/17/s --manifest-globs endpoints-extension-dev.json src/*.json --loc-root /home/adminuser/agent03/_work/17/s --overrides-file /tmp/PackageTask-0.631205.tmp --output-path /home/adminuser/agent03/_work/17/a/dist/dev/mypublisher.endpoints-dev.vsix 0 [ '[command]/home/adminuser/agent03/_work/_tools/node_modules/.bin/tfx extension create --json --no-color --root /home/adminuser/agent03/_work/17/s --manifest-globs endpoints-extension-dev.json src/*.json --loc-root /home/adminuser/agent03/_work/17/s --overrides-file /tmp/PackageTask-0.631205.tmp --output-path /home/adminuser/agent03/_work/17/a/dist/dev/mypublisher.endpoints-dev.vsix',
  '' ]
 1 [ '[command]/home/adminuser/agent03/_work/_tools/node_modules/.bin/tfx extension create --json --no-color --root /home/adminuser/agent03/_work/17/s --manifest-globs endpoints-extension-dev.json src/*.json --loc-root /home/adminuser/agent03/_work/17/s --overrides-file /tmp/PackageTask-0.631205.tmp --output-path /home/adminuser/agent03/_work/17/a/dist/dev/mypublisher.endpoints-dev.vsix',
  '' ]
error: Error: No manifests found from the following glob patterns: 
error: endpoints-extension-dev.json src/*.json
##[debug]task result: Failed
```
I tried the following values for `patternManifest` without success:
 - `endpoints-extension-dev.json src/*.json`
 - `endpoints-extension-dev.json ./src/*.json`
 - `endpoints-extension-dev.json **/src/*.json`

If I omit the second part, and just set the value to `endpoints-extension-dev.json`, I get a standard error message, telling me that there's no contributions in the extension, which is true.

Any idea why I get this error?
Thanks

**Comment by jessehouwing** [comment]
Not sure, I've never tried separating the manifests.

It may have to do with the fact that we run tfx with a different working directory. Try prefixing the globs with `$(Build.SourcesDircetory)/src/*.json`

**Comment by BiribiriJaNai** [comment]
@jessehouwing thanks for the advice. I tried but still no luck and I didn't notice any particular logs from tfx-cli.
For now, I'll just stick to my scripts.

**Comment by jessehouwing** [comment]
Any chance your project is available on GitHub so I can play?

**Comment by BiribiriJaNai** [comment]
I had to do a little cleanup because it was on a corporate VSTS account, but you can find a working copy here: https://github.com/BiribiriJaNai/vso-endpoints

**Comment by jessehouwing** [comment]
I think I've found the root cause. The way this value is interpreted at th emoment we send:

```
--manifestglobs "pattern pattern pattern"
```

but should send

```
--manifestglobs "pattern" "pattern" "pattern"
```

Need to think about how to solve this.

**Comment by jessehouwing** [comment]
https://github.com/Microsoft/vsts-extension-build-release-tasks/blob/master/BuildTasks/Common/Common.ts#L44

Proposed solution:

 - [ ] change manifest to a multi-line edit box
 - [ ] break string on lineends
 - [ ] pass all globs as an array

**Comment by jessehouwing** [comment]
This has been released to the marketplace.
