### ISSUE TITLE
Publish Visual Studio Extension usability feedback: file picker vs. directory picker + file name input

### ISSUE THREAD

**Issue by henrybeen** [Microsoft/vsts-extension-build-release-tasks#118]
For the Visual Studion Extension publish task. It feels confusing to have a (neat) file picker to select the location of the .vsix file. Why can't the same be done for the Manifest file? Why is this split over a directory picker and an input for the filename? Wouldn't a single file picker do the trick? Especially since only the first match for the directory + filename pattern is picked up?

**Comment by jessehouwing** [comment]
@onlyutkarsh feedback?

**Comment by onlyutkarsh** [comment]
@henrybeen fair feedback. I tried to reuse the logic used to search for the manifest file. But what you saying makes sense. I should probably make the change. 

@jessehouwing To not to break the existing builds using this task, I think this should be in the next version of the task. But I see, we don't deliver multiple versions of the tasks as of today - Thoughts?

**Comment by jessehouwing** [comment]
It's preview. I'm not hesitant to break things while in preview.

**Comment by henrybeen** [comment]
Breaking things is never fun, but I would prefer a break in this case over a quick increase in versions.
