### ISSUE TITLE
Avoid partially succeeded state when install fails (because it is already installed)

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/vsts-extension-build-release-tasks#12]
Feedback from user via the Marketplace (https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks#review-details) ..

> Great set of tasks, helped out big time with our CI release process.   However, it would be nice to have an option to ignore "Error: Failed Request: Conflict(409) - TF1590010: Extension is already installed in this account" error. I'd prefer to not to have the task listed as partially succeeded. We want as part of our release process to ensure the extension is installed to our various target environments and if it's already installed, that's ok.

**Comment by bfcamara** [comment]
A previous version of tfx-cli was checking explicitly for the 409 status and ignoring the error in that case, and just setting the message in report status as "Alreasdy Installed". It seems that tfx-cli isn't doing that anymore

https://github.com/Microsoft/tfs-cli/commit/7c8ef36677c61b77779a0fb30179a901bb2f23d3
