### ISSUE TITLE
Support Canary Deployment for a Private Extension

### ISSUE THREAD

**Issue by swansonaj** [Microsoft/vsts-extension-build-release-tasks#129]
Can I use the Share Extension task to do a canary deployment for a private Azure DevOps extension? My extension is shared with a dozen or so organizations and now I need to update it. However, I would like to do a canary deployment to 1 or 2 organizations that are willing to validate the update before sharing it with the rest of the organizations. From what I read, the Azure DevOps Marketplace will immediately share the update with all organizations that have the extension installed as soon as I publish an update. If I use the Share Extension task to only share my update with 1 or 2 organizations will it override the default behavior of the Marketplace?

**Comment by jessehouwing** [comment]
No it will not. The share extension only adds a new shared org. If you want
to do canary releases you need to add another private extension with
another extension ID and publish that first.

**Comment by swansonaj** [comment]
My extension has custom build/release pipeline tasks in it. If I want to publish another private extension would I need to generate new GUIDs for those tasks so as not to conflict with the existing extension? I guess I am not sure if the task GUIDs have to be unique within the marketplace or just unique within the extension itself.

**Comment by jessehouwing** [comment]
No you wouldn't. As long as the tasks are private and by the same publisher
it should work!

**Comment by swansonaj** [comment]
@jessehouwing Thank you for your prompt answers -- they helped. I have more questions but I don't think this is the right forum. Is there somewhere else you recommend I go for Q&A about the Azure DevOps extension marketplace as well as packaging/publishing extensions?

**Comment by jessehouwing** [comment]
Join here - Me and a lot of other extension developers are over there.
https://teamservices.club/
