### ISSUE TITLE
Publish Extension task does not support wild cards

### ISSUE THREAD

**Issue by MrHinsh** [Microsoft/vsts-extension-build-release-tasks#17]
The Publish task extension should allow me to enter "*_/nkdAgility.vsts-sync-migration-_.vsix" so that I don't have to use a variable just to load the file...

**Comment by jessehouwing** [comment]
I looked at how  other tasks do this, but while it's very easy in Powershell (find-vstsfiles), it's quite unclear in the Typescript tasks... I'll check with Bryan to see what the right way is... Generally I don't want a base path + pattern textbox, as that would break the compatibility.

**Comment by MrHinsh** [comment]
Just fix it

**Comment by jessehouwing** [comment]
Want to fix it right. I'm already talking to Eric and Bryan to get the correct sample.

**Comment by jessehouwing** [comment]
As soon as the 2.0.0 version of the Typescript SDK is released, I'll have an easy way to add this in and not worry about backwards compatibility. Until then, use the Output Variable to capture the filename and optionally rename it if you want.

**Comment by jessehouwing** [comment]
Starting on this:
https://github.com/Microsoft/vsts-extension-build-release-tasks/tree/users/jessehouwing/matchVsixPattern

**Comment by jessehouwing** [comment]
Just merged with master. Awaiting publish approval.
