### ISSUE TITLE
http://servername:8080/tfs/DefaultCollection/_apis/gallery broken with TFS 2017

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/vsts-extension-build-release-tasks#20]
Any attempt to publish results in an unknown URL because the REST API seems to have changed.

**Comment by jessehouwing** [comment]
I'd hazard a guess (not in a position to test at the moment) that the gallery lives at the server level and not at the collection level:
```
http://servername:8080/tfs/_gallery
```

**Comment by jessehouwing** [comment]
Updated inline documentation for better explanation.
