### ISSUE TITLE
TFS Local Gallery connection - configurable over variables

### ISSUE THREAD

**Issue by aumanjoa** [Microsoft/vsts-extension-build-release-tasks#33]
Hey Team,

I have the following use case:

I am using the publish Extension task to publish an extension to a TFS.
In my Release definiton I have different stages for different TFS instances (TEST/PROD).

I have not found a way to use a variable for the "TFS Local Gallery connection" field. 
I want to overwrite this variable for each environment. 

What I tried so far was to put the "resorceID" from the Service Endpoints. e.g. "12346789-1234-1234-12345678912345678" into the variable. 

I always get this error message in the log even when the endpoint id is correct 

 ##[error]Error running task: Error: Endpoint not present: 12346789-1234-1234-12345678912345678

I hope you can tell me how I can solve the problem and what value I have to put into my environmentVariable. 

Cheers,

Joachim

**Comment by jessehouwing** [comment]
I don't think this is currently technically possible. @willsmythe can you chime in on this or verify with the folks from the Build and Release team?

**Comment by jessehouwing** [comment]
Pinging a few folks to see if they know: @bryanmacfarlane @chrisrpatterson @trevorsg

**Comment by jessehouwing** [comment]
I assume this is what you tried:
![image](https://cloud.githubusercontent.com/assets/4173387/21566105/e9ec3714-ce9f-11e6-9a85-6f1a33323398.png)

And for the folks I pinged, the variable is trying to configure Connected Service.

**Comment by aumanjoa** [comment]
Thanks @jessehouwing  that is exactly what I tried but using the Team Foundation Server not VSTS, but I think that don't matter so much. 

It would be very helpfull because I think its a common case that someone try to parameterize this

**Comment by jessehouwing** [comment]
I think you're the first. I for one have never tried this before. It seems
to be something that could be considered a bug in the agent... In which
case it may be useful to post an issue to the vsts-agent project. The
service connection functionality is standard, I'm not doing anything
special.

**Comment by aumanjoa** [comment]
So you can reproduce the issue on your side? and you can confirm what needed to be in the value is the resourceId?

**Comment by jessehouwing** [comment]
I'm assuming the service id, I took the value from the json representation
of the build and saved that to a variable.

I get the same behavior as you. I tried both the service name (which isn't
unique anyway, so I expected that to fail) and the Guid. I get the exact
same al error you get.

**Comment by jessehouwing** [comment]
Reply from the release management team. 

>Jesse,
>If I understand, you are trying to define service end point as a variable and use it in the tasks for service connections.
 
>Today, this is not possible. You have to have different endpoints for each environment with different values and use them in the appropriate environment.
 
 
>Thanks
>Gopinath

**Comment by jessehouwing** [comment]
Confirmed by the build team as well.
