### ISSUE TITLE
Local Gallery Configuration with TFS 2015 Update 2 On Premise

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vsts-extension-build-release-tasks#41]
I've got the need to add a new TFS local gallery connection endpoint, but am having trouble finding documentation on how to configure the build/release task extension by setting up this local gallery connection. As I'm on TFS Onpremise Update 2, I believe I'm required to use Basic Authentication. However, before I create any specific user I'm unclear if there is any issue in running in our intranet with encryption/ssl to protect the credentials. 

Any guidance would be appreciated as I'm unable to find anything on this for the extension. The "more info" link in TFS Onpremise for this dialogue [opens to the latest documentation]( https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate) which seems to focus on personal access tokens, which we can't use at this time.

**Comment by jessehouwing** [comment]
My recommendation would be to upgrade to TFS 2017 and use the PAT features
therein.

Alternatively you can setup an NTLM proxy in your build agent that would
handle the upgrade from basic to NTLM.

If you enable basic auth you have a few options, we highly recommend
enabling ssl to protect your credentials. The disadvantage of turning in
basic auth is that most users will be prompted to enter their credentials
every time, as automatic windows auth will no longer work.

Alternatively you could setup a second application tier and enable basic
auth on that. Then point your build agent to use its machine name to
connect.
