### ISSUE TITLE
Build is not getting queued when 'VSTS Developer Tools Build Tasks' is added in TFS 2017 build definition

### ISSUE THREAD

**Issue by ranuka2** [Microsoft/vsts-extension-build-release-tasks#47]
I have entered all required parameters and saves the task, When I clicked the “Queue new build” link it shows error message “There are issues with the request or definition….”, When I disable the task and Queue a build again it works fine. Please advise how to resolve this. 

TFS Version : TFS 2017
Task Version: 1.1.41
Input file type: VSIX file

**Comment by jessehouwing** [comment]
It looks like you're using the "Publish task"? Have you tried removing and re-adding the task?

Please post the Build Definition json for this task:
![image](https://cloud.githubusercontent.com/assets/4173387/23206790/5052cdbe-f8ef-11e6-8cfd-508e37d39473.png)

Like this, that should tell me exactly what values are configured:
![image](https://cloud.githubusercontent.com/assets/4173387/23206761/34b4b31a-f8ef-11e6-8691-08b8a619d91a.png)

And what also could help is if you can intercept the json reply that's generated when queueing the build using your browser developer tools or fiddler. It may contain more information about the issues with the definition.

If you want to send them offline, please send it to: jhouwing@xpirit.com.

**Comment by jessehouwing** [comment]
I just tested the publish task on TFS 2017u1RC and that works as expected. I do get an error that my agent doesn't have npm installed, do you have Node installed and added to the %path% of the system or the service user so the build can find it?

**Comment by ranuka2** [comment]
@jessehouwing , 

Json from build definition:
   ```
 {
      "enabled": true,
      "continueOnError": false,
      "alwaysRun": false,
      "displayName": "Publish Extension",
      "timeoutInMinutes": 0,
      "task": {
        "id": "xxx-xxx-xxx-xxx-xxx",
        "versionSpec": "*",
        "definitionType": "task"
      },
      "inputs": {
        "connectTo": "VsTeam",
        "connectedServiceName": "xxx-xxx-xxx-xxx-xxx",
        "connectedServiceNameTFS": "",
        "fileType": "vsix",
        "vsixFile": "C:\\Test\\Test.vsix",
        "rootFolder": "",
        "localizationRoot": "",
        "patternManifest": "vss-extension.json",
        "publisherId": "xxxxx",
        "extensionId": "",
        "extensionTag": "",
        "extensionName": "",
        "extensionVersion": "",
        "updateTasksVersion": "false",
        "extensionVisibility": "private",
        "extensionPricing": "free",
        "outputVariable": "",
        "shareWith": "",
        "arguments": "",
        "cwd": ""
      }
    }
```

Node server is installed in the TFS server and other build tasks are getting executed correctly.

Thank you,
Ranuka

**Comment by jessehouwing** [comment]
Not seeing anything that stands out from the json that helps me diagnose the issue. Next step would be to get a fiddler trace from trying to queue the build when the definition is in broken state.

**Comment by ranuka2** [comment]
@jessehouwing : Found the issue Jesse, Issue is Node path was not added as you mentioned. Thank you.
