### ISSUE TITLE
"Automatically link new work in this build" does not work

### ISSUE THREAD

**Issue by mmulhearn** [Microsoft/vsts-extension-build-release-tasks#53]
The Build Definition option to "Automatically link new work in this build" does not work (this option was released 5/11, https://www.visualstudio.com/en-us/articles/news/2017/may-11-team-services#automatic-linking-from-work-items-to-builds). When enabling via the web UI, there is no option below it to "only link to work added to specific branches." There appears to be a small UI change, but the option does not appear. It seems it tried to show the configuration present in the release notes, but something is breaking it. This is the HTML that gets generated:

&lt;div&gt;&lt;div&gt;&lt;div&gt;&lt;div&gt;&lt;div role="list"&gt;&lt;div&gt;&lt;div&gt;&lt;div role="listitem" data-list-index="0" data-automationid="ListCell"&gt;&lt;!-- react-empty: 785 --&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;

Furthermore, enabling the option does nothing to link the work item to the build. It links to the changeset, but not the build.

https://developercommunity.visualstudio.com/content/problem/74066/automatically-link-new-work-in-this-build-does-not.html

**Comment by jessehouwing** [comment]
This is unrated to the build tasks to package and release extensions. You should probably file this under vsts-agent or on the Visual Studio developer  community.
