### ISSUE TITLE
Add support for proxy settings

### ISSUE THREAD

**Issue by IPO-srh-sloan** [Microsoft/vsts-extension-build-release-tasks#58]
The extension seems to ignore the system proxy so I can't use it on our on-prem vsts agents. I have tried using the `arguments` field on the publish extension task but this seems to be ignored so is not getting passed to tfx.

Could you either please fix the `arguments` field or add a proxy field that gets passed to `--proxy`?

**Comment by jessehouwing** [comment]
Setting the environment variable 'HTTP_PROXY' should be automatically
picked up. Creating a build variable HTTP.PROXY should do the trick.

I'll have a look at the args input.

**Comment by jessehouwing** [comment]
I've double checked the arguments and they were not working when publishing from VSIX. That's fixed now. I'll see if I can pass in the proxy automatically.

**Comment by jessehouwing** [comment]
Hmz... I'd like to add proxy support. But don't have a situation where proxy is required. The agent can be configured with a proxy and I can fetch those details, but it doesn't seem like I can pass in a URL to hav it test whether the proxy is required, so I suppose that you'd want the proxy to have UI as well.

Is setting the Environment variable good enough?

**Comment by jessehouwing** [comment]
@willsmythe @wpschaub Would adding something like this make sense?

```
export function setProxy() {
    const proxy = tl.getHttpProxyConfiguration();

    if (!process.env["HTTP_PROXY"] && !process.env["HTTPS_PROXY"]) {
        let proxyUrl = new uri(proxy.proxyUrl);
        if (proxy.proxyUsername) {
            proxyUrl.username(proxy.proxyUsername);
            proxyUrl.password(proxy.proxyPassword);
        }
        process.env["HTTP_PROXY"] = proxyUrl;
        process.env["HTTPS_PROXY"] = proxyUrl;

        if (!process.env["NO_PROXY"]) {
            process.env["NO_PROXY"] = proxy.proxyBypassHosts;
        }
    }
}
```

**Comment by jessehouwing** [comment]
@IPO-srh-sloan I'd love to be able to send you an experimental test version...

**Comment by jessehouwing** [comment]
https://github.com/Microsoft/vsts-extension-build-release-tasks/tree/features/auto-proxy

**Comment by IPO-srh-sloan** [comment]
@jessehouwing Sorry for the delay, I've been off. Happy to test if you can send me a test version?

**Comment by jessehouwing** [comment]
VSTS or TFS? Attached a custom TFS build. If you're on VSTS I need you account name so I can share. 
[vsix.zip](https://github.com/Microsoft/vsts-extension-build-release-tasks/files/1772682/vsix.zip)

**Comment by IPO-srh-sloan** [comment]
Could you share it with ukipo-dev.visualstudio.com please?

**Comment by jessehouwing** [comment]
Done

**Comment by jessehouwing** [comment]
@IPO-srh-sloan any feedback?

**Comment by IPO-srh-sloan** [comment]
Sorry, only just had a chance to look. It does now seem to be reading in the system proxy with no extra settings - is that what you were expecting? Thanks.

**Comment by jessehouwing** [comment]
That's what I'd expect. Does it work as well, that's the most important thing ;).

BTW you can also set these environment variables on the agent itself to make them apply for any Node based task.

**Comment by IPO-srh-sloan** [comment]
Yes, it does work when reading in the system proxy :)

**Comment by jessehouwing** [comment]
I did some checking and it's preferred to use the default Node/VSTS environment variables over the task trying to magically compute them.
