### ISSUE TITLE
publishing widget results in error  Error: Validation timed out. There may be a problem validating your extension. Please try again later.

### ISSUE THREAD

**Issue by davesmits** [Microsoft/vsts-extension-build-release-tasks#59]
since the new validation process very often my releases are failing because this error:
 Error: Validation timed out. There may be a problem validating your extension. Please try again later.

most of the times the extionsions will be published; just takes a little longer. can the time out in the build task be increased?

**Comment by jessehouwing** [comment]
I'll dig into this. There seems to be a commandline argument to ignore validation, let me reach out to the folks behind the marketplace to see what options we have.

**Comment by wpschaub** [comment]
@jessehouwing it's back. Our Work Item Details build is failing with "Validation Timed Out". We re-ran the release and it failed with "version needs to increment". That's when I received an email confirming successful validation of the first attempt, which failed according to pipeline.
- [RELEASE OVERVIEW](https://almrangers.visualstudio.com/ALM/_release?definitionId=15&definitionEnvironmentId=44&_a=environment-summary)

**Comment by davesmits** [comment]
nicest would be the timeout would be longer; not to ignore the validation because then when things go wrong you wont see in release manager

**Comment by jessehouwing** [comment]
@wpschaub hands are tied here. Needs tfx support. I'm just wrapping what they provide.

**Comment by jessehouwing** [comment]
Looks like 0.5.5 version of tfx is ignoring the `--no-wait-validation` completely...

**Comment by jessehouwing** [comment]
Just released a new version of the tools that pass the `--no-wait-validation` flag along. The latest version of `tfx` should now honour this flag for private extensions as well.

And with that I've also released a new Wait for Validation task that can be used on the Agent or as a Server Gate in release management. This will wait (up to a specified timeout) for validation to succeed and will update the status of the Build / Release accordingly.

![image](https://user-images.githubusercontent.com/4173387/38749947-9ef99df2-3f53-11e8-914e-63c274496ac1.png)
![image](https://user-images.githubusercontent.com/4173387/38749953-a3945500-3f53-11e8-8022-a791035a5363.png)
![image](https://user-images.githubusercontent.com/4173387/38749973-b2917768-3f53-11e8-8149-fb92427959b1.png)

The Release Gate will require you to enable the "Release Gate" preview flag for the VSTS account.

**Comment by davesmits** [comment]
Nice! well done!
