### ISSUE TITLE
Package Extension: Extension Version Override Incorrect behavior

### ISSUE THREAD

**Issue by bstearns** [Microsoft/vsts-extension-build-release-tasks#7]
I am currently trying to package an extension during my build using the Package Extension task.
I am seeing an issue when I set the Extension Version Override value to $(Build.BuildNumber).
When by build number format is set to the following: $(MajorVersion).$(MinorVersion).$(Year:yy)$(DayOfYear).$(Rev:rrr)

When I do this the package is created as I would expect.  The problem arises after I publish the extension and share it with my VSTS account.  

When I try then to add any of the tasks included in the created extension they are not available.

The interesting part of this is that if I just fill in the Extension Version Override with a constant such as 0.0.0.66 and regenerate the package and republish.  I am able to see all of the tasks as expected.

**Comment by jessehouwing** [comment]
I suspect the year+dayofyear is too long to fit in an unsigned short. Can
you publish manually using the values and 'tfx build tasks upload'?

**Comment by bstearns** [comment]
As the year is $(Year:yy) and day the largest that the number would get this year would be 16354 which is well under the 65535 limit of a unsigned short. Even so, I ran another test where I tried to fill in the Extension Version Override with a constant which was equivalent to the generated build number to see if that would work and it did not.  With that result and that the publish does work with a constant of 0.0.0.66 it does seem that you are probably onto the issue with some sort of overrun on the numbers.  Can you confirm that it is an unsigned short that it is value is limited to?


 Just for your information,  the publish that I am doing is not using the VSTS extension task at this point.  I am downloading the package from the build artifacts and then publishing through the https://marketplace.visualstudio.com/manage/publishers/  interface.

Thanks for the quick feed back.  These tasks are really helpful.

**Comment by jessehouwing** [comment]
Pinged the Microsoft team to have a look, this is something that's internal to the marketplace.

**Comment by jessehouwing** [comment]
To be sure, @bstearns the Build/Release tasks are the part of the extension that break, right?

**Comment by bstearns** [comment]
@jessehouwing   I was having problems when the package is published.  I will have another look at it in the next few days to confirm exactly  where the problem  lies.  I have not looked at this in a couple months so need to confirm the problem still exists.

**Comment by willsmythe** [comment]
Can someone provide an example of an extension version number that exhibits this problem? (i.e. publishes and installs OK, but the task fails to appear)

**Comment by jessehouwing** [comment]
Closing the issue due to lack of feedback.
