### ISSUE TITLE
Extension manifest: baseuri http scheme invariant 

### ISSUE THREAD

**Issue by keesschollaart81** [Microsoft/vsts-extension-build-release-tasks#71]
I'm hosting my extensions files remote using the [baseUri](https://docs.microsoft.com/en-us/vsts/extend/develop/manifest?view=vsts#runtime-attributes) property. By default I set this property with my HTTPS based url.

When users use my extension in TFS Server their TFS server might not use HTTPS and because of that they get errors: https://github.com/keesschollaart81/vsts-sprint-goal/issues/8

When I change my baseurl to start with ```//my.hostname/...``` instead of ```https://my.hostname/...``` the extension does not load at all.

**Comment by jessehouwing** [comment]
This question is more about extension development, than about the CI/CD tasks to publish extensions. 

Your available support options:

 * email vsointegration@microsoft.com
 * submit an issue on: https://developercommunity.visualstudio.com/spaces/21/index.html
