### ISSUE TITLE
When extension version variable is empty, use manifest version

### ISSUE THREAD

**Issue by pabrams** [Microsoft/vsts-extension-build-release-tasks#76]
I thought I could use these tasks to avoid the problem of my extension releases failing on the first time they are published/installed (or if not then, then on all subsequent times), without having to create separate build or release definitions (for first-time and not-first-time extension installations).

In the Publish Extension task, there is a "Extension version" field, and it says "If not specified, the extension version specified in the manifest will be used", which would be great, but I guess it only means if I put nothing in the field.  I put a variable in there, but when that variable is empty, the task fails:

>  ##[error]Error running task: Error: Supplied ExtensionVersion must contain a string matching '##.##.##(.##)'.

Could this use manifest version when empty?  Would that even be appropriate?  Or do you have a suggestion for how I can handle this?  

(The "Query extension version" task has a similar problem:  it throws an error if the extension doesn't exist, but I was willing to live with the "partially succeeded" deployment on the very first publish.)

**Comment by jessehouwing** [comment]
Hmm interesting. Is the variable empty... Or not configured? In the first
case the task receives an empty string, in the second it received the
unexpanded variable name...

I'm currently not able to change this behavior until I return from a trip.

**Comment by pabrams** [comment]
Ah sorry, think I was just using the wrong notation - using $() around variable name when I shouldn't have, or not using it when I should have.
