### ISSUE TITLE
Installing Extensions no longer works

### ISSUE THREAD

**Issue by jhandel** [Microsoft/vsts-extension-build-release-tasks#8]
We haven't made any changes to security or our deployment, (haven't used it in a few weeks) but as of today our release fails at Install Extension with the followng 403 error
- : [Failed: Error: Failed Request: Forbidden(403) - Access Denied: [user name] needs the following permission(s) to perform this action: Edit instance-level information]

**Comment by bfcamara** [comment]
I think it's related with this issue

https://github.com/Microsoft/tfs-cli/issues/141

**Comment by trevorsg** [comment]
Yeah, definitely related. We're looking into it. ETA is next week.

**Comment by omeshp** [comment]
Any update on this issue, currently our CDP is broken because of this breaking change.

**Comment by trevorsg** [comment]
I'm working on the fix today, but it's not quite a straightforward fix. Hopefully I'll have an update published by the end of the day.
