### ISSUE TITLE
 UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jdholbrook81** [Microsoft/vsts-extension-build-release-tasks#82]
Started getting the warning below on publish today. Went back and tried executing a previously successful release, same error. Executing against "Hosted" agent. Looks like the node version has incremented from 1.1.72 to 1.1.75 since this was successful.

2018-08-14T18:09:05.9311356Z ##[warning]Removing Unicode BOM from manifest file: C:\Users\BUILDG~1\AppData\Local\Temp\vsixeditor118714-3700-x6w330.gshismunmi\Tasks\ITSMIntegration\task.json.
2018-08-14T18:09:05.9320566Z (node:3700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'split' of undefined

The task is marked as successful, but nothing is deployed and I do not get the " Published VSIX" line at the end of the log.

**Comment by jessehouwing** [comment]
Awhile bunch of things have changed. Can you tell me which properties you
have overwritten or give me a debug log (system.debug=true) of the task?

**Comment by jdholbrook81** [comment]
[tasklog_4.log](https://github.com/Microsoft/vsts-extension-build-release-tasks/files/2288327/tasklog_4.log)

attached

**Comment by jdholbrook81** [comment]
Thanks, that did the trick.

**Comment by jessehouwing** [comment]
Will close after fixing the actual error. Thanks for confirming. Fixing a bug in these tasks can be hard when publishing them is broken ;).
