### ISSUE TITLE
Task Id replacement doesn't work when using task versions

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-extension-build-release-tasks#83]
https://github.com/Microsoft/vsts-extension-build-release-tasks/blob/7e4486c4681e45412a06cd2859c1f65fa85ad737/BuildTasks/Common/Common.ts#L519

There are two issues:

1. If the contribution in the vss-extension.json does not end in a forward slash it does not search the correct directory.
2. The directory being searched is incorrect as **taskRoot** is joined in the path twice.

**Comment by jessehouwing** [comment]
Both are correct an both are wrong. I've used the convention used on the multi version manifest page, but I believe it doesn't even have to be v1, V2, v3, simply any folder should work.

**Comment by gregpakes** [comment]
@jessehouwing 

Ah ok - I have done mine slightly differently to the multi-version manifest page (https://docs.microsoft.com/en-gb/vsts/extend/develop/build-task-schema?view=vsts#bundle-multiple-versions-of-build-tasks-within-one-extension):

- Tasks
  - TaskName
    - V1
      - .....
    -V2

So I could adjust my PR to search any sub folder?  Would that be better?

**Comment by gregpakes** [comment]
I have adjusted the PR to reflect this change.  it will now search all sub dirs for task.json.

https://github.com/Microsoft/vsts-extension-build-release-tasks/pull/84

**Comment by gregpakes** [comment]
I understand what you’re saying, but there is a disconnect between what is documented and what is possible.

I know of other extensions that are done differently to the documentation.

For example:

https://github.com/rfennell/vNextBuild/tree/master/Extensions/XplatGenerateReleaseNotes
