### ISSUE TITLE
error: Received response 401 (Not Authorized).

### ISSUE THREAD

**Issue by petertownsend** [Microsoft/vsts-extension-build-release-tasks#90]
Getting this error when trying to publish to Marketplace. 
2018-09-20T08:38:53.9213932Z error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.
2018-09-20T08:38:53.9488093Z ##[error]tfx failed with error: Error: D:\a\_tools\tfx.cmd failed with return code: 4294967295

However I know the personal access token is correct. So it's definitely not an issue with the PAT. Any ideas on what could be the issue? I'm able to upload the vsix file (before it is processed by this extension fine)

**Comment by Geronius** [comment]
I've got the same problem. Has anyone a solution?

**Comment by jessehouwing** [comment]
Does it work with the same pat from the commandline?

**Comment by petertownsend** [comment]
I was getting the same error running from the command line, finally found the issue - when you create the pat token, in the organisations drop down make sure its "All accessible [your org] organizations" - then it worked for me....
