### ISSUE TITLE
Update blocked asking for new permissions?

### ISSUE THREAD

**Issue by lukewis** [Microsoft/vsts-extension-build-release-tasks#91]
I received a notification this morning saying that the update of this extension was blocked until I authorized additional required scopes ("Update blocked pending authorization of new scopes").  However, when I click the "Authorize" button, it does not list any additional new scopes (notice that nothing is listed after the colon).
```
A new version of CI/CD Tools for VSTS Extensions is available and now requires these permissions:

By clicking Authorize, you authorize this extension on behalf of all users in this organization.
```
Can you help me understand:

1. What scopes are currently authorized for this extension (can't find a way to view this)
2. What NEW scopes are now required (Authorize dialog doesn't specify any)?

**Comment by jessehouwing** [comment]
You can see the old permissions here:

https://github.com/Microsoft/vsts-extension-build-release-tasks/commit/f12d4b5a170f58b8ad060ddf8a065c93f92e121e#diff-807f48e9e32f775acf3cc8ec88d5a518
