### ISSUE TITLE
Publishing fails with extension already exists

### ISSUE THREAD

**Issue by KiranBabu-Kirando** [Microsoft/vsts-extension-build-release-tasks#93]
![705f6c16](https://user-images.githubusercontent.com/26311305/46705273-9efa0400-cbe3-11e8-827d-002aad69e115.PNG)
We are getting this exception for past couple of weeks. Not able to publish updates to our extension.

exception:
Failed request: Conflict(409) - The extension already exists.

**Comment by jessehouwing** [comment]
Try manually uploading the extension through the portal to see if you get a
clearer error message. The error is returned from the marketplace, so it
looks like the task is doing its job.
