### ISSUE TITLE
Change credential storage on linux to use the system keyring or utilise AES256 at a minimum

### ISSUE THREAD

**Issue by term1n4l** [Microsoft/vsts-extension-build-release-tasks#94]
Please change the credential storage on Linux to:

a) use the Gnome keyring (probably better as more widely used) or the KDE Wallet for credential storage (if possible as an additional feature), 
b) the file should be encrypted with an AES256 hash and a user specified password at the very least.

This is a pretty big security issue as relying on user perms to secure a plain text file (regardless of where stored and how 'hidden' it is, is pretty poor. This demonstrates a pretty big knowledge gap in both security and the Linux operating system.

**Comment by jessehouwing** [comment]
Can you provide a little more context? It looks like this issue belongs in another issue tracker, or I don't understand the problem as it relates to the tasks in this repository.

**Comment by term1n4l** [comment]
This is in reference to the vsts extension storing credentials in Linux in the user profile in the ~/.team/team-secrets.json file. As referenced in https://blogs.msdn.microsoft.com/devops/2016/07/11/the-team-services-extension-for-visual-studio-code-now-supports-team-foundation-server-2015-update-2-and-later/

**Comment by term1n4l** [comment]
Hmm probably not for this repo now that I have reviewed the readme, the repo name kinda looks like it relates to the bats extension specifically
