### ISSUE TITLE
Set publisher id and extension id for vertical navigation icons in vsomanifest

### ISSUE THREAD

**Issue by florianbader** [Microsoft/vsts-extension-build-release-tasks#95]
The new Azure DevOps navigation (vertical navigation) supports setting an icon for each hub. The icon must be specified with a fully qualified asset name which includes the publisher id and extension id. Currently, this extension only updates the vsixmanifest, which makes it impossible to specify a navigation icon if the publisher id and or extension id changes.

see https://docs.microsoft.com/en-us/azure/devops/extend/develop/web-navigation?view=vsts#hub-icon

If you need help with implementing this one, I can contribute the changes as a pull request to update the icon asset name in the vsomanifest for this specific case.

**Comment by jessehouwing** [comment]
Ideally this should be fixed in tfx, it has the option to override the
extensionId and the Publisher ID.

Let me first get in touch with the folks on the product team, this feels
like a bug in the specs.

**Comment by jessehouwing** [comment]
So far looks like people are on my side :). But that doesn't help you yet. Current recommendation is to put this as a pre-package script in your pipeline and to publish from source instead of vsix.

**Comment by florianbader** [comment]
Thanks for looking into this. I guess I leave out the icon for now because I really like the idea of building one package and publishing it to different environments with different extension ids.

**Comment by jessehouwing** [comment]
Feedback from @willsmythe confirms my belief. Not sure when this is fixed on the extension side though.
